/**
 * Baseline policy for the visual regression suite.
 *
 * @remarks
 * Extracted from `visual-regression.test.mjs` so the three policy rows of the
 * story's edge-case matrix — over-threshold, missing baseline, deliberate
 * regeneration — are verifiable without a running app. That file launches the
 * real Tauri binary in `beforeAll`, which cannot happen on macOS at all
 * (`tauri-driver` has no WKWebView driver), so policy that lives inside it is
 * policy nobody can test on a Mac.
 *
 * The comparison itself is not reimplemented here: `compareRgbaPixels` from
 * the export goldens stays the only definition of "the same picture".
 */

import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { dirname } from 'node:path';
import { compareRgbaPixels } from '../../../../packages/renderer-webgl/test/export-goldens/harness.mjs';
import { decodePngToRgba } from '../../../../packages/renderer-webgl/test/export-goldens/png-to-rgba.mjs';

/** Writes the capture beside its baseline so a failure can be looked at. */
export async function writeActual(baselinePath, capture) {
  const actualPath = baselinePath.replace(/\.png$/, '.actual.png');
  await mkdir(dirname(actualPath), { recursive: true });
  await writeFile(actualPath, capture.bytes);
  return actualPath;
}

/**
 * Compares one capture against its committed baseline.
 *
 * @param options.capture - `{ width, height, pixels, bytes }` as produced by
 * `decodePngToRgba` plus the original PNG bytes.
 * @param options.baselinePath - Absolute path of the committed PNG.
 * @param options.maxDifferentPixelRatio - Threshold, read from the goldens' manifest.
 * @param options.updateBaselines - When true, writes the baseline and then
 * throws: a regenerating run can never be green, so a new baseline is always a
 * reviewed diff rather than something a passing pipeline quietly accepted.
 * @param options.describePath - Renders a path for the error message.
 * @throws When the baseline is missing, its dimensions differ, the delta
 * exceeds the threshold, or `updateBaselines` is set.
 */
export async function compareAgainstBaseline({
  capture,
  baselinePath,
  maxDifferentPixelRatio,
  updateBaselines = false,
  describePath = (path) => path,
}) {
  if (updateBaselines) {
    await mkdir(dirname(baselinePath), { recursive: true });
    await writeFile(baselinePath, capture.bytes);
    throw new Error(
      `Baseline written to ${describePath(baselinePath)}. Review the image, ` +
        'commit it, and re-run without VELLUM_E2E_UPDATE_BASELINES so the ' +
        'comparison actually runs.',
    );
  }

  const baselineBytes = await readFile(baselinePath).catch(() => null);
  if (!baselineBytes) {
    // Never autogenerated: a baseline that appears by itself is a picture of
    // whatever the code happened to do, not a decision anyone made.
    throw new Error(
      `Missing baseline ${describePath(baselinePath)}. Generate it explicitly ` +
        'with VELLUM_E2E_UPDATE_BASELINES=1 pnpm test:e2e, then review and ' +
        'commit the PNG — see apps/desktop/tests/e2e/baselines/README.md.',
    );
  }

  const baseline = decodePngToRgba(baselineBytes);
  if (baseline.width !== capture.width || baseline.height !== capture.height) {
    await writeActual(baselinePath, capture);
    throw new Error(
      `Capture is ${capture.width}x${capture.height} but ` +
        `${describePath(baselinePath)} is ${baseline.width}x${baseline.height}. ` +
        'The window size changed; the baseline has to be regenerated deliberately.',
    );
  }

  try {
    compareRgbaPixels(capture.pixels, baseline.pixels, {
      dimensions: { width: baseline.width, height: baseline.height },
      maxDifferentPixelRatio,
    });
  } catch (error) {
    const actualPath = await writeActual(baselinePath, capture);
    throw new Error(
      `Capture differs from ${describePath(baselinePath)}: ${error.message}. ` +
        `Capture written to ${describePath(actualPath)}.`,
    );
  }
}
